### ISSUE TITLE
Support for non-ascii image paths

### ISSUE THREAD

**Issue by CendaL** [marcapelini/RTProfileSelector#1]
RTPProfileSelector cannot work with non-ascii paths - see RT params file [CPB_temp_0.txt](https://github.com/marcapelini/RTProfileSelector/files/740325/CPB_temp_0.txt) which contains:
```
[RT General]
ImageFileName=D:\\Photos\\2016\\12-24 Vánoce\\raw\\IMG_8883.CR2
OutputProfileFileName=D:\\Photos\\2016\\12-24 Vánoce\\raw\\IMG_8883.CR2.pp3
```

Log: [RTProfileSelector.log.zip](https://github.com/marcapelini/RTProfileSelector/files/740345/RTProfileSelector.log.zip)
```
Calling exiftool: C:\Dos\RTProfileSelector\exiftool.exe -t -m -q -q "D:\Photos\2016\12-24 Vánoce\raw\IMG_8882.CR2" > C:\Users\lukas\AppData\Local\RawTherapee\cache\IMG_8882.txt
Could not read Exif keys from image file: D:\Photos\2016\12-24 Vánoce\raw\IMG_8882.CR2
```

It works fine when I rename `12-24 Vánoce` to `12-24 Vanoce`.

**Comment by marcapelini** [comment]
It's been more than two years since I last compiled RTProfileSelector for Windows.  I don't think it was too particular about filenames or paths, but I certainly did not use Unicode or wide char strings to handle paths, so there may well be some problems.

> C:\Dos\RTProfileSelector\exiftool.exe -t -m -q -q "D:\Photos\2016\12-24 Vánoce\raw\IMG_8882.CR2" > C:\Users\lukas\AppData\Local\RawTherapee\cache\IMG_8882.txt

One question: did you also try to run the the command above from a command prompt window? If so, was the "IMG_8882.txt" ever created? Just curious, as the problem might actually be concerned with exiftool rather than RawTherapee. If you can, please do try and report back here.

Thanks!

**Comment by CendaL** [comment]
Yes, the above command runs fine and produces C:\Users\lukas\AppData\Local\RawTherapee\cache\IMG_8882.txt.

I'm sure the problem is with not using Unicode/wide char strings - I have run it in debugger and I saw the wrong string `ImageFileName=D:\\Photos\\2016\\12-24 VĂˇnoce\\raw\\IMG_8883.CR2`. Unfortunately, I cannot fix it as I don't know C++ :-(

**Comment by marcapelini** [comment]
@CendaL please check release 1.0.3c for a correction (more like a workaround) and see if it works for you. If it does, I'll close the issue. Thanks!

**Comment by CendaL** [comment]
It works - thanks a lot!

**Comment by CendaL** [comment]
**I just want to highlight your clever fix!**

I hit another folder where it did not work - `Pec pod Sněžkou` but thanks to the possibility to specify default locale in the ini file, I was able to fix it:
```
[General]
DefaultLocale=.1250
```

**Comment by marcapelini** [comment]
Great! Shame on  me for not documenting the new config key, but fortunately you were able to dig it up yourself :)
