### ISSUE TITLE
Logging, issue + improvement

### ISSUE THREAD

**Issue by polezhaevdmi** [marcapelini/RTProfileSelector#3]
OS: Windows 7 x64
After processing phase found these strings in the log file:
> Error copying source -> destination profile:
> "C:\Program Files\RawTherapee\profiles"\\\"Canon EOS 5D Mark III.pp3" -> D:\PHOTO\Simeiz 201603\IMG_2749.CR2.pp3

However, the profile was copied as should.
The effect does not depend of profile naming, "Canon EOS 5D Mark III.pp3" or Canon EOS 5D Mark III.pp3
Seems, something wrong with copy procedure. Should the destination path be doublequoted before procedure call?

And is it possible to extend the scope of events logged? For example:
- The section match, but the profile does not exist at the desired place;
- Copying/Merging sections from list of profiles.
This will help to debug faster.

Still, a lot of thanks for the utility, Marc!

**Comment by marcapelini** [comment]
Some improvement to the logs is something I've wanted to do for some time! I agree that currently the logs are of very limited use for diagnosing problems in RTPS.  Maybe next time I get to work on the code, in a few week's time...

**Comment by polezhaevdmi** [comment]
Marcos, I wish You to be able to enjoy the code improvement with no interference to Your main tasks.
Have a plenty of time and a lot of money!

**Comment by polezhaevdmi** [comment]
Tried to completely simplify the names. In vain.

> Error copying source -> destination profile:
> D:\INSTALL\Imaging\RTProfileSelector\Canon_EF_24_70mm_f_2_8L.pp3 -> D:\PHOTO\IMG_2749.CR2.pp3
>

**Comment by marcapelini** [comment]
The last couple of commits hope to improve info logging and debugging. 
-  Log file (RRProfileSelector.log) now prints the name of the selected base profile, as well as the list of partial profiles matched based on "partial rules". Example:
```
Base profile file selected: /home/mc/.config/RawTherapee5-dev/profiles/Pana Modes/Pana_Expressive.pp3
Including partial profile: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80 - basic.pp3
Including partial profile: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
Including partial profile: /home/mc/.config/RawTherapee5-dev/profiles/Lens Profiles/lens_auto_correction.pp3
```
- A file named 'LastPP3Debug.txt' is generated in the same directory as the application. This file is essentially a "PP3" profile with a comment before each entry indicating the source file for that particular entry. Example:
```
; Base profile file: /home/mc/.config/RawTherapee5-dev/profiles/Pana Modes/Pana_Expressive.pp3
[Version]
; source: /home/mc/.config/RawTherapee5-dev/profiles/Pana Modes/Pana_Expressive.pp3
AppVersion=5.3
; source: /home/mc/.config/RawTherapee5-dev/profiles/Pana Modes/Pana_Expressive.pp3
Version=327
...
[CACorrection]
; source: /home/mc/.config/RawTherapee5-dev/profiles/Lens Profiles/lens_auto_correction.pp3
Blue=0
; source: /home/mc/.config/RawTherapee5-dev/profiles/Lens Profiles/lens_auto_correction.pp3
Red=0
...
[Crop]
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
Enabled=true
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
FixedRatio=true
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
Guide=None
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
H=2588
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
Orientation=As Image
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
Ratio=16:9
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
W=4600
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
X=0
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80_crop_16x9.pp3
Y=434
...
[Directional Pyramid Denoising]
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80 - basic.pp3
Bluechro=15.379997253417969
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80 - basic.pp3
C2Method=AUTO
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80 - basic.pp3
CCCurve=1;0.050000000000000003;0.5;0.34999999999999998;0.34999999999999998;0.34999999999999998;0.050000000000000003;0.34999999999999998;0.34999999999999998;
; source: /home/mc/.config/RawTherapee5-dev/profiles/Camera Specific/GX80 - basic.pp3
CMethod=MAN

```
These changes make it easier to check which profiles were selected, in what order they were applied, and to find out exactly from which files (=which rules) each entry in the generated PP3 file came from.
