### ISSUE TITLE
Preprocessing ISO and lens distortion file names

### ISSUE THREAD

**Issue by polezhaevdmi** [marcapelini/RTProfileSelector#6]
The EXIF identification strings might contain symbols, which might interfere with filesystem object naming conventions, for example: **_\ / - , : ._** and so on. 
Proposition: replace all non-literal and non-digit characters with underscores, to avoid possible problems with files iso.*.ini and lens.*.ini files access in Linux or Windows.
Thus, we will use "iso.DMC_GM1.ini" instead of "iso.DMC-GM1.ini", and "lens.Canon_EF_24_70mm_f_2_8L.ini" instead of "Canon EF 24-70mm f/2.8L".

**Comment by marcapelini** [comment]
You do have a point, but I'm not a big fan of replacing reserved characters by underscore or any other fixed character, as I've had problems with this approach in the past (i.e., filename conflicts).  Windows is known for being fussy about certain characters in paths, but do you have any particular example of EXIF fields (particularly camera & lens IDs) causing problems? The example you gave (with a hyphen/dash) wouldn't cause a problem even on Windows.

**Comment by polezhaevdmi** [comment]
Let's see. Windows 7 x64 sp2+.

Command CLI - problem with folder or file name

> mkdir "Canon EF 24-70mm f/2.8L"
> dir 
> 13.06.2017  20:07    DIR          Canon EF 24-70mm f
> D:\TEMP>echo !!! >"Canon EF 24-70mm f/2.8L.txt"
> The system cannot find the path specified.

FAR - the same behaviour;
Explorer - creates fine.
So, the result ALREADY depends of API used. Even in a such simple case.
In addition, I'm very paranoid, and afraid the Lenses with EXIF ID like "GoodLens 4-4000 mm /0.95 <Nano> &1|STAB" will appear at our times. :)

**Comment by marcapelini** [comment]
Lens distortion and ISO parameters file names are now protected from using reserved characters according to target OS (from [stackoverflow](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) answer):
- Windows: 
```< (less than)
> (greater than)
: (colon - sometimes works, but is actually NTFS Alternate Data Streams)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```
- Linux/Unix:
```
/ (forward slash)
```

Reserved characters found in EXIF tag values for camera and lens models are now replaced with a single underscore ('_') each for generating the corresponding "lens.<CAMERA OR LENS MODEL/>.ini" (likewise for ISO files).
