### ISSUE TITLE
Error during processing RT 5.8 key file?

### ISSUE THREAD

**Issue by polezhaevdmi** [marcapelini/RTProfileSelector#7]
Sorry for the disturbance, Marcos.

What might cause the RTPS fail to process the key or ini file in such case? 
Now RTPS invokes fine, but, seems, has a problem parsing the passed information. As a result, the .pp3 file is created with valid [RT General] info (at least), but does not have desired RAW development recipe parameters. 
The log at that point has almost nothing, and the debugging program (notepad) is not activating.
I attached all files, which might be helpful.
Now I'm using the published 1.0.5 version, not compiled by myself.

[LastKeyFile.txt](https://github.com/marcapelini/RTProfileSelector/files/5960841/LastKeyFile.txt)
[RTProfileSelector.log](https://github.com/marcapelini/RTProfileSelector/files/5960842/RTProfileSelector.log)
[RTProfileSelector.ini.txt](https://github.com/marcapelini/RTProfileSelector/files/5960872/RTProfileSelector.ini.txt)

**Comment by marcapelini** [comment]
It seems your "default processing profile" in RT is not properly set, as per the wiki instructions for RTPS.

From your "LastKeyFile.txt", I can see your default profile is "Neutral", which is a "bundled profile", not a custom one:

_[RT General]
CachePath=C:\\Users\\USRWS\\AppData\\Local\\RawTherapee\\cache
AppVersion=5.8
ProcParamsVersion=346
ImageFileName=D:\\PHOTO\\Desna202008\\IMG_9410.CR2
OutputProfileFileName=D:\\PHOTO\\Desna202008\\IMG_9410.CR2.pp3
DefaultProcParams=**Neutral**
FlaggingMode=false_

Please take a look at the [instructions](https://github.com/marcapelini/RTProfileSelector/wiki/Integrating-with-RawTherapee) for integrating RTPS with RT. About halfway down the page there's this note:

> Make sure you have at least one custom processing profile (placed within "My Profiles" in RT) and that it is set as your default profile. **This is necessary for RTPS to automatically detect the folder where RT stores its custom profiles**, so that you can later assign rules for them. If you don't have any custom profiles, or your current default profile is not a custom one, you can enter that information manually in RTPS's configuration file (see below), but the automatic method is preferable.

The reason this is needed it that RT does not inform the location of the custom profiles to any custom builder program, and RTPS needs this to find the profiles used by its rules.

**Comment by polezhaevdmi** [comment]
Exactly, You are right. My faults were:
- I made a conclusion the manually configured path to custom profiles completely overrides the configuration for automatic method;
- I used the double quotes in path to custom profiles (as it 'long' in terms of Windows). 
After I fixed the first mistake, the second was identified by the log messages:

_Base profile file selected: "C:\Program Files (x86)\RTProfileSelector"\Canon_EOS_5D_Mark_III.pp3
Error opening base profile file: "C:\Program Files (x86)\RTProfileSelector"\Canon_EOS_5D_Mark_III.pp3
Error applying rules - operation aborted!_

Now RTPS selects profiles fine. Thank You!

**Comment by marcapelini** [comment]
> _Error opening base profile file: "C:\Program Files (x86)\RTProfileSelector"\Canon_EOS_5D_Mark_III.pp3_
> _Error applying rules - operation aborted!_
> 
> Now RTPS selects profiles fine. Thank You!

Now I'm confused: you say the profile selection works fine now, but you seem to get error messages as shown above.  Can you elaborate?

Anyway, I'm working on a few changes to try to make RTPS compatible with [Art](https://bitbucket.org/agriggio/art/wiki/Home), and will try to improve the log message in case RT has been (mis)configured to use a bundled profile as default, which lead to your original problem.

**Comment by polezhaevdmi** [comment]
@marcapelini, no: I said the error messages above were help me to fix the second mistake with double quotes. After second fix the RTProfileSelector.ini file became correct (attached it), thus, RTPS started to operate fine.

[RTProfileSelector.ini.txt](https://github.com/marcapelini/RTProfileSelector/files/5973934/RTProfileSelector.ini.txt)

In addition I tried these weird experiments:
1. Set the profile in RT to "Neutral" again, leaving the RTProfileSelector.ini file correctly configured. Got the initial error and made a conclusion my mistakes are influencing RTPS independently.
2. Set the profile in RT correctly to my custom made one, but added an extra space to the end of RTCustomProfilesPath parameter. That resulted with second error, but the message looked funny:
_Base profile file selected: C:\Program Files (x86)\RTProfileSelector \Canon_EOS_5D_Mark_III.pp3
Error opening base profile file: C:\Program Files (x86)\RTProfileSelector \Canon_EOS_5D_Mark_III.pp3_
Maybe, some 'fool-proofing manipulations' with strings for ExifTool, ExifTextViewer and RTCustomProfilesPath parameters would be welcome...

Special thanks for the link to Art! It worth to be investigated!

**Comment by marcapelini** [comment]
> @marcapelini, no: I said the error messages above were help me to fix the second mistake with double quotes. After second fix the RTProfileSelector.ini file became correct (attached it), thus, RTPS started to operate fine.

All it's well that ends well! ;)

> Special thanks for the link to Art! It worth to be investigated!

I'm starting to explore ART myself.  Alberto has been doing a great job with it.  There was a problem with ART though where it wasn't calling the custom profile builder (I thought it was my mistake).  He was going to push a patch to correct it.  I compiled ART with his patch and can report that RTPS works fine with the ".arp" files, which are the same as .pp3 files are for RT, but lots of parameter keys and sections different, so .pp3 files are not ART-compatible (which was probably the reason he changed the extension).  I'm re-doing some of my .pp3 profiles as .arp and I can say I rather like ART so far...
